sched-ext: introduce the concept of performance profiles
CachyOS/kernel-manager pull request #19
Opened 2024-08-24 13:31 UTC by arighi

Add an extra combo box to select the "performance profile" for the currently selected sched-ext scheduler. The selected profile will be automatically converted into the appropriate flags for the chosen scheduler.

Currently, only scx_bpfland and scx_lavd are supported, so the additional combo box will be visible only when one of these schedulers is selected.

2024-08-24 18:33 UTC, ptr1337 approved these changes
Thanks for adding this!

Tested-by: Peter Jung <ptr1337@cachyos.org>

2024-08-25 18:00 UTC, vnepogodin requested changes

2024-08-25 18:00 UTC, vnepogodin commented on src/schedext-window.cpp
> +    const auto& scheduler = m_ui->schedext_combo_box->currentText().toStdString();
`.toStdString();` can be removed here, as we don't really need std::string instance QString is fine here

2024-08-25 18:00 UTC, vnepogodin commented on src/schedext-window.cpp
> +        std::string scx_base_flags;
that can be made std::string_view because base flags are static and known at compile-time

2024-08-25 18:00 UTC, vnepogodin commented on src/schedext-window.cpp
> +        if (scx_profile == "default") {
for strings we should use string_view literals because we "import" them earlier in the lambda.
```suggestion
        if (scx_profile == "default"sv) {
```

2024-08-25 18:00 UTC, vnepogodin commented on src/schedext-window.cpp
> +                scx_base_flags = "-c 0 -k -m performance";
```suggestion
                scx_base_flags = "-c 0 -k -m performance"sv;
```

in other places in that lambda also

2024-08-25 18:01 UTC, vnepogodin commented
also run `clang-format -i src/*.cpp` to format according to style

2024-08-26 11:57 UTC, arighi commented
@vnepogodin PR updated with (I think) all your suggestions applied, thanks!

2024-08-26 12:22 UTC, vnepogodin approved these changes
Many thanks!

2024-08-26 12:22 UTC, merged